### PR TITLE
Completed Apple website clone

### PR DESCRIPTION
**Pull request by DennisOsido**
Live Preview Link: https://rawcdn.githack.com/DennisOsido/Apple-Website-Clone/0f9989b1bb7d484899e8701a1bb4e62576dd17ca/index.html

## EDIT after the third review:
- Removed all Image Tags on HTML and made them as CSS Background Images
- Made Image to Occupy entire browser and removed scrolling
- Improved Gradient of Navbar

## EDIT after the second review:
- Improved Responsiveness for 1366 x 768p screens

## EDIT after the first review:
- Restructured Layout to Grid
- Instead of 1 Big Image, I replaced it with an image for each section
- Added Linear Gradients to navbar

Steps:
Added Background Image
Added Navbar
Added Footer
Added Main Body Text
Added Links and Hover Effects

Project Layout Requirements that were completed:
Flex and Float were used

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @DennisOsido 
### Good job so far for the work done :clap: However, you have a few changes to work on before your project can be approved.
- The project focuses more on background and gradient, therefore, you need to use a gradient as background for the navigation items
nav
- Also, make your website go full width. Don't leave margins on the left and right
- Add images in the css stylesheet, not in the html
css
### [NOTE]
- You downloaded the reference website as an image and added it to yours as a background, note this not accepted. You are required to build this section by section as a replica, make the changes as required
background
mainimage


### Make these changes and resubmit for another code review. Good luck!
- For assistance, contact me on slack: @iamraymond
- Happy coding!

**Comment by DennisOsido** [comment]
## After the first review:
- Restructured Layout to Grid
- Instead of 1 Big Image, I replaced it with an image for each section
- Added Linear Gradients to navbar

**Comment by thsvr** [comment]
### **Status: Changes required**


Hi @DennisOsido :smiley: :smiley: 


Your job looks great and you are almost done, so I will show a few changes required that are not done yet, so please read it carefully and do the changes before submit it again for another review.

:v: As required by TSE Raymond, can you please remove the white margins on the left and right?

white-margin




:v: The images are crashing with each other, can you fix it in order to show all the content on the images?

images-crashing




:v: On the footer, note the links are crashing each other. Can you please please fix it?

footer-apple



 
If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)




**Happy coding** :computer:  **and good luck on the next review** :memo: 


Thaís Vieira (TSE)

**Comment by DennisOsido** [comment]
## After the 2nd review:

- Improved Responsiveness for 1366 x 768p screens

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :hands

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work! @DennisOsido 
You have done a solid job putting this together and handling proposed changes. Please consider my comments below, make the appropriate changes, and request another review! I wish you the best and see you at the top :medal_military: 

#### Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
screenshot

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing). Consider the screen below
screenshot

#### Navigation Bar
Great job implementing the gradient in the navigation bar, however, it only looks a little similar to the original page's navigation. I encourage you to consider working on it some more, for one, it will make your page look much cooler and you will learn a lot more!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by DennisOsido** [comment]
## After the third review:
- Removed all Image Tags on HTML and made them as CSS Background Images
- Made Image to Occupy entire browser and removed scrolling
- Improved Gradient of Navbar

**Comment by lekegitrepo** [comment]
This **PR** is under Review by: **_[TSE] Temitayo Adeleke_**

**Comment by lekegitrepo** [comment]
Hi @DennisOsido 🥇 
Well done. I'm approving this project, as you have made the required changes mentioned by the last reviewer. Good luck with your next project.

Reviewed by: Temitayo Adeleke
-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Pull request merged**
